module.exports = {

    // FIREBASE ACTIONS
	FIREBASE: "",

	// UI ACTIONS
    // USER DRAWER
    SHOW_CONTACTS_SIDEBAR: "SHOW_CONTACTS_SIDEBAR",


	// AUTH ACTIONS
	// ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	// LOGIN_USER: "LOGIN_USER",
	// LOGOUT: "LOGOUT",

	// AUTH STATES
	// LOGGED_IN: "LOGGED_IN",
	// ANONYMOUS: "ANONYMOUS",
	// AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// Conversations
    START_NEW_CONVERSATION: "START_NEW_CONVERSATION",
    TOGGLE_CONVERSATION: "TOGGLE_CONVERSATION",
    ADD_CONVERSATION : "ADD_CONVERSATION",
    UPDATE_CONVERSATION_HEADER: "UPDATE_CONVERSATION_HEADER",
    
    // MESSAGES
    ADD_MESSAGE: "ADD_MESSAGE",

};